### ISSUE TITLE
怎么接入微信小游戏呢？

### ISSUE THREAD

**Issue by ponyfe** [ThinkingDataAnalytics/unity-sdk#3]
看这个源码好像没办法接入微信小游戏呢？官方文档也没有找到支持unity接入小游戏的相关描述。

**Comment by ThinkingDataAnalytics** [comment]
> 看这个源码好像没办法接入微信小游戏呢？官方文档也没有找到支持unity接入小游戏的相关描述。
这个是可以支持的，需要的话可以联系下我们的CSM
